name: Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"

      - name: Set up Goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Run build script
        run: ./scripts/buildprod.sh

      - name: Migrate data
        run: ./scripts/migrateup.sh

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - name: Push to Google Artifact Registry
        run: gcloud builds submit --tag us-east1-docker.pkg.dev/notely-bootdev/notely-ar-repo/notely:latest .

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image us-east1-docker.pkg.dev/notely-bootdev/notely-ar-repo/notely:latest --region us-east1 --allow-unauthenticated --project notely-bootdev --max-instances=4
